# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-02 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170902_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='couvertures'),
        ),
        migrations.AddField(
            model_name='book',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='quantite',
            field=models.IntegerField(null=True),
        ),
    ]
